apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: bt5kza5tr-nodejs 
  janus-idp.io/tekton: bt5kza5tr-nodejs
  backstage.io/kubernetes-id: bt5kza5tr-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: bt5kza5tr-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml